const copy = {
  ru: {
    'nav.work':'кейсы','nav.about':'обо мне','nav.contact':'контакты',
    'hero.copy':'Креатор и creative strategist. Разрабатываю спецпроекты, бренд-активации, промо и события: концепция, механика, визуальное направление, тексты и защита.',
    'hero.meta1':'International brands · Luxury · FMCG · Tech','hero.meta2':'Federal promo · brief up to 50M ₽ · NCP','hero.meta3':'Moscow · Remote worldwide','hero.scroll':'листать ↓',
    'scale.s1':'luxury, beauty, FMCG, tech','scale.s2':'стартовый бюджет федерального promo-тендера','scale.s3':'one winning platform adapted across major retailers','scale.s4':'wins, selection, second rounds, rollout',
    'manifesto.eyebrow':'как я работаю','manifesto.a':'КОНЦЕПТ','manifesto.b':'МЕХАНИКА','manifesto.c':'ПРОСТРАНСТВО','manifesto.d':'ТЕКСТ','manifesto.e':'ПИТЧ','manifesto.f':'ПРОДАКШЕН',
    'manifesto.note':'Работаю от брифа до защиты идеи: собираю creative territory, механику, guest/user journey, визуальное направление и тексты. Площадку, бюджет и ограничения продакшена учитываю уже на этапе концепта.',
    'brands.title':'selected brands / clients / retail','brands.note':'Названия брендов показаны отдельно от NDA-кейсов. Связь конкретного бренда с конкретным проектом публично не раскрывается.',
    'outcomes.title':'масштаб и результаты','outcomes.o1':'стартовый бюджет выигранного федерального promo-тендера','outcomes.o2':'крупных retail-сетей получили адаптации исходной winning-платформы','outcomes.o3':'концепции выбраны в одном multi-brand luxury brief','outcomes.o4':'FMCG-бренда в одной winning phygital-интеграции','outcomes.o5':'гостей в двухдневном event-брифе международной beauty-компании','outcomes.o6':'promo, retail, digital, events и special projects',
    'work.eyebrow':'selected work / NDA-safe edit','work.title':'Избранные проекты.<br/>Luxury, FMCG, tech, events.',
    'labels.role':'моя роль','labels.outcome':'результат','labels.scale':'масштаб',
    'case1.tag':'Luxury retail · 4 international fragrance brands','case1.title':'Сезонные retail-активации для 4 fragrance-брендов','case1.lead':'Для каждого бренда — отдельная концепция корнера: visual code, traffic stopper, retail animation, GWP и сценарий контакта с ароматом.','case1.role':'creative territories · mechanics · copy · gifting · pitch deck','case1.scale':'4 international brands · seasonal retail brief','case1.outcome':'2 из 4 концепций выбраны',
    'case2.tag':'Luxury · client days · retail','case2.title':'Holiday client days / Opera Night','case2.lead':'Концепция праздничных клиентских дней: визуальная территория Opera Night, décor, gifting и активации вокруг аромата.','case2.role':'concept · storytelling · activation ideas · décor direction · copy','case2.scale':'international luxury brand · retail client experience','case2.outcome':'winning concept',
    'case3.tag':'Phygital · FMCG · culture','case3.title':'Phygital-интеграция для 3 FMCG-брендов','case3.lead':'Онлайн + офлайн интеграция в танцевальный чемпионат: бренд-зоны, транзакционная механика, merch и роли брендов по ходу participant journey.','case3.role':'concept · integration system · mechanics · merch · copy','case3.scale':'3 brands · online + offline · national phygital event','case3.outcome':'winning pitch / selected for production',
    'case4.tag':'Tech · employer brand · festival','case4.title':'Employer-brand активация на food-фестивале','case4.lead':'Концепция бренд-зоны: интерактивы, chill-area, mocktail bar, branded food и social-механики.','case4.role':'concept · spatial mechanics · copy · activation ideas · pitch','case4.scale':'major tech brand · large food festival','case4.outcome':'часть предложенных элементов реализована',
    'case5.tag':'FMCG · federal promo · music × retail','case5.title':'Federal summer promo / music × retail','case5.lead':'Победившая концепция федерального летнего промо. Стартовый бюджет тендера — 50 млн ₽. После победы исходную платформу адаптировали под несколько крупных retail-сетей.','case5.role':'core creative platform · promo mechanics · copy · pitch','case5.scale':'federal promo · 50 млн ₽ initial tender brief · 5 major retail chains','case5.outcome':'winning core concept · later adapted across 5 chains','case5.proof':'стартовый бюджет федерального тендера',
    'case6.tag':'Corporate event · international beauty','case6.title':'Двухдневное событие / 100 гостей','case6.lead':'Несколько концепций для внутреннего события: визуальная система, вечерняя программа, тимбилдинг и сценарий дня.','case6.role':'concept territories · event mechanics · copy · presentation','case6.scale':'100 гостей · бюджет брифа 5 млн ₽','case6.outcome':'проект прошёл во второй тур',
    'about.eyebrow':'обо мне','about.title':'Креатив.<br/>Спецпроекты.<br/>Стратегия.','about.p1':'Я агентский креатор: 360°-кампании, спецпроекты, ивенты, retail и brand experience. В опыте — international luxury, beauty, FMCG и tech-бренды, федеральные промо и тендерные брифы до 50 млн ₽.','about.p2':'Подключаюсь к проекту от брифа и поиска идеи до механики, текстов, презентации и защиты. Люблю задачи, где концепцию нужно не только придумать, но и приземлить в реальную площадку, бюджет и продакшен.','about.p3':'До журналистики училась дизайну в НИУ ВШЭ. Поэтому в проектах думаю не только текстом: работаю с визуальной логикой, композицией, пространством, референсами и арт-дирекшном.',
    'startup.eyebrow':'beyond agency / startup','startup.title':'ACE — стартап для международной студенческой аудитории.','startup.copy':'Соосновательница Academic Card for Everything. С нуля занималась маркетингом, визуальной айдентикой, сайтом, SMM и коммуникацией продукта; работала рядом с разработчиками, презентовала проект в разных странах и участвовала в привлечении инвесторов.','startup.m1':'CO-FOUNDER / MARKETING','startup.m2':'IDENTITY / WEB / SMM','startup.m3':'INTERNATIONAL / PRODUCT-ADJACENT',
    'practice.eyebrow':'design / tools / practice','practice.title':'Текст — только один из инструментов.','practice.copy':'Могу собрать идею как систему: narrative, визуальный язык, структура презентации, key message, mockups и AI-assisted визуальные прототипы. Продвинутый Adobe; собственные AI-workflows, включая ComfyUI; базовый код.',
    'nda.copy':'Большая часть работ создавалась в агентской среде и защищена NDA. Поэтому отдельные бренды, бюджеты, механики и визуальные материалы в кейсах обезличены или адаптированы. Подробности о моей роли могу обсудить лично.',
    'contact.eyebrow':'контакты','contact.title':'Спецпроект, тендер<br/>или запуск?<br/>Пишите.','contact.top':'наверх ↑'
  },
  en: {
    'nav.work':'work','nav.about':'about','nav.contact':'contact',
    'hero.copy':'Creative strategist working across special projects, brand activations, promotions and events — concept, mechanics, visual direction, copy and pitch.',
    'hero.meta1':'International brands · Luxury · FMCG · Tech','hero.meta2':'Federal promo · briefs up to RUB 50M · NCP','hero.meta3':'Moscow · Remote worldwide','hero.scroll':'scroll ↓',
    'scale.s1':'luxury, beauty, FMCG, tech','scale.s2':'initial budget of a federal promo tender','scale.s3':'one winning platform adapted across major retailers','scale.s4':'wins, selection, second rounds, rollout',
    'manifesto.eyebrow':'how I work','manifesto.a':'CONCEPT','manifesto.b':'MECHANICS','manifesto.c':'SPACE','manifesto.d':'COPY','manifesto.e':'PITCH','manifesto.f':'PRODUCTION',
    'manifesto.note':'I work from brief to pitch: creative territory, mechanics, guest/user journey, visual direction and copy. Venue, budget and production constraints are considered from the concept stage.',
    'brands.title':'selected brands / clients / retail','brands.note':'Brand names are shown separately from NDA-protected case studies. Individual brands are not publicly connected to specific projects.',
    'outcomes.title':'scope & outcomes','outcomes.o1':'initial budget of a winning federal promo tender','outcomes.o2':'major retail chains received adaptations of the original winning platform','outcomes.o3':'concepts selected within one multi-brand luxury brief','outcomes.o4':'FMCG brands in one winning phygital integration','outcomes.o5':'guests in a two-day event brief for an international beauty company','outcomes.o6':'promo, retail, digital, events and special projects',
    'work.eyebrow':'selected work / NDA-safe edit','work.title':'Selected work.<br/>Luxury, FMCG, tech, events.',
    'labels.role':'my role','labels.outcome':'outcome','labels.scale':'scale',
    'case1.tag':'Luxury retail · 4 international fragrance brands','case1.title':'Seasonal retail activations for 4 fragrance brands','case1.lead':'A separate retail concept for each brand: visual code, traffic stopper, retail animation, GWP and fragrance-discovery mechanic.','case1.role':'creative territories · mechanics · copy · gifting · pitch deck','case1.scale':'4 international brands · seasonal retail brief','case1.outcome':'2 of 4 concepts selected',
    'case2.tag':'Luxury · client days · retail','case2.title':'Holiday client days / Opera Night','case2.lead':'A holiday client-days concept built around the Opera Night visual territory, décor, gifting and fragrance activations.','case2.role':'concept · storytelling · activation ideas · décor direction · copy','case2.scale':'international luxury brand · retail client experience','case2.outcome':'winning concept',
    'case3.tag':'Phygital · FMCG · culture','case3.title':'Phygital integration for 3 FMCG brands','case3.lead':'Online + offline integration into a dance championship: brand zones, transactional mechanics, merch and distinct brand roles across the participant journey.','case3.role':'concept · integration system · mechanics · merch · copy','case3.scale':'3 brands · online + offline · national phygital event','case3.outcome':'winning pitch / selected for production',
    'case4.tag':'Tech · employer brand · festival','case4.title':'Employer-brand activation at a food festival','case4.lead':'Brand-zone concept with interactive mechanics, a chill area, mocktail bar, branded food and social elements.','case4.role':'concept · spatial mechanics · copy · activation ideas · pitch','case4.scale':'major tech brand · large food festival','case4.outcome':'selected elements were produced',
    'case5.tag':'FMCG · federal promo · music × retail','case5.title':'Federal summer promo / music × retail','case5.lead':'Winning concept for a national summer promotion. The initial tender budget was RUB 50M. After the win, the core platform was adapted across several major retail chains as the project moved into production.','case5.role':'core creative platform · promo mechanics · copy · pitch','case5.scale':'federal promo · RUB 50M initial tender brief · 5 major retail chains','case5.outcome':'winning core concept · later adapted across 5 chains','case5.proof':'initial federal tender brief',
    'case6.tag':'Corporate event · international beauty','case6.title':'Two-day event / 100 guests','case6.lead':'Several concepts for an internal two-day event: visual system, evening programme, team-building and day flow.','case6.role':'concept territories · event mechanics · copy · presentation','case6.scale':'100 guests · RUB 5M brief budget','case6.outcome':'advanced to the second round',
    'about.eyebrow':'about','about.title':'Creative.<br/>Special projects.<br/>Strategy.','about.p1':'I’m an agency creative working across 360 campaigns, special projects, events, retail and brand experience. My work includes international luxury, beauty, FMCG and tech brands, federal promotions and tender briefs up to RUB 50M.','about.p2':'I work from brief and idea development through mechanics, copy, presentation and pitch. I’m most interested in concepts that also have to work within a real venue, budget and production process.','about.p3':'Before journalism, I studied design at HSE University. That background shapes how I work: not only with copy, but with visual logic, composition, space, references and art direction.',
    'startup.eyebrow':'beyond agency / startup','startup.title':'ACE — a startup for an international student audience.','startup.copy':'Co-founded Academic Card for Everything. Built marketing, visual identity, the website, social media and product communication from scratch; worked closely with developers, presented the project across countries and contributed to investor outreach.','startup.m1':'CO-FOUNDER / MARKETING','startup.m2':'IDENTITY / WEB / SMM','startup.m3':'INTERNATIONAL / PRODUCT-ADJACENT',
    'practice.eyebrow':'design / tools / practice','practice.title':'Copy is only one of the tools.','practice.copy':'I can build an idea as a system: narrative, visual language, presentation structure, key message, mockups and AI-assisted visual prototypes. Advanced Adobe; custom AI workflows including ComfyUI; basic code.',
    'nda.copy':'Most of the work featured here was developed within an agency environment and is protected by NDA. Certain brand names, budgets, mechanics and visuals have therefore been anonymised or adapted. I’m happy to discuss my individual contribution privately.',
    'contact.eyebrow':'contact','contact.title':'Special project, pitch<br/>or launch?<br/>Get in touch.','contact.top':'back to top ↑'
  }
};

const langButton = document.querySelector('.lang');
let current = 'ru';
function renderLanguage(lang) {
  current = lang;
  document.documentElement.dataset.lang = lang;
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (copy[lang][key]) el.innerHTML = copy[lang][key];
  });
  langButton.textContent = lang === 'ru' ? 'EN' : 'RU';
  localStorage.setItem('portfolioLang', lang);
}
langButton.addEventListener('click', () => renderLanguage(current === 'ru' ? 'en' : 'ru'));
renderLanguage(localStorage.getItem('portfolioLang') || 'ru');

